import React from 'react';
import { StyleSheet } from 'react-native';

export const authenticationStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#f5f5f5',
    },
    input: {
        width: '80%',
        padding: 12,
        margin: 8,
        borderWidth: 1,
        borderRadius: 8,
        borderColor: '#ddd',
        backgroundColor: '#fff',
    },
    button: {
        width: '80%',
        padding: 12,
        margin: 8,
        borderRadius: 8,
        alignItems: 'center',
        backgroundColor: '#3f51b5',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
    registerButton: {
        marginTop: 8,
    },
    registerButtonText: {
        color: '#3f51b5',
        textDecorationLine: 'underline',
    },
    inputError: {
        width: '80%',
        padding: 12,
        margin: 8,
        borderWidth: 1,
        borderRadius: 8,
        borderColor: '#ff0000',
        backgroundColor: '#fff',
    },
    errorText: {
        color: '#ff0000',
        marginVertical: 5,
        backgroundColor: '#ffe5e5',
        borderRadius: 5,
        padding: 5,
        borderWidth: 1,
        borderColor: '#ffcccc',
        textAlign: 'left',
        width: '80%',
        alignSelf: 'center',
    },
    buttonDisabled: {
        width: '80%',
        padding: 12,
        margin: 8,
        borderRadius: 8,
        alignItems: 'center',
        backgroundColor: '#cccccc',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
});
